# Generated by Django 5.2.12 on 2026-03-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("documentario", "Documentário"),
                            ("institucional", "Institucional"),
                            ("educacional", "Educacional"),
                            ("branded", "Branded Content"),
                            ("outro", "Outro"),
                        ],
                        default="documentario",
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "bunny_embed_url",
                    models.URLField(
                        help_text="Cole aqui a URL de embed do Bunny Stream (ex: https://iframe.mediadelivery.net/embed/...)",
                        verbose_name="URL do Player Bunny",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="URL da imagem de capa. Se vazio, usa um placeholder.",
                        verbose_name="URL da Thumbnail",
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Destaque na home"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Vídeo",
                "verbose_name_plural": "Vídeos",
                "ordering": ["ordem", "-criado_em"],
            },
        ),
    ]
