# Generated by Django 5.2.12 on 2026-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="thumbnail_url",
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Imagem de capa do vídeo. Recomendado: 16:9 (ex: 1280×720).",
                upload_to="videos/thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
