# Generated by Django 5.2.12 on 2026-03-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_video_thumbnail_url_video_thumbnail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "subtitulo",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Subtítulo"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("arte", "Livro de Arte"),
                            ("fotografia", "Fotografia"),
                            ("documentario", "Documentário"),
                            ("institucional", "Institucional"),
                            ("educacional", "Educacional"),
                            ("outro", "Outro"),
                        ],
                        default="arte",
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "capa",
                    models.ImageField(
                        help_text="Foto principal do livro para o card. Recomendado: 3:4 (ex: 600×800).",
                        upload_to="livros/capas/",
                        verbose_name="Imagem de Capa",
                    ),
                ),
                (
                    "ano",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ano de publicação"
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Autor(es)"
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Destaque na home"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
                "ordering": ["ordem", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="FotoLivro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        help_text="Foto do livro (páginas, detalhes, etc).",
                        upload_to="livros/fotos/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legenda"
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="core.livro",
                        verbose_name="Livro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do Livro",
                "verbose_name_plural": "Fotos do Livro",
                "ordering": ["ordem"],
            },
        ),
    ]
