# Generated by Django 5.2.12 on 2026-03-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_livro_fotolivro"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="bunny_video_url",
            field=models.URLField(
                blank=True,
                help_text="URL direta do arquivo MP4 no Bunny CDN (ex: https://vz-XXXXX.b-cdn.net/VIDEO_ID/play_720p.mp4). Usada como vídeo de fundo no hero.",
                verbose_name="URL direta do vídeo (MP4)",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="bunny_embed_url",
            field=models.URLField(
                help_text="URL de embed do Bunny Stream (ex: https://iframe.mediadelivery.net/embed/...)",
                verbose_name="URL do Player Bunny (iframe)",
            ),
        ),
    ]
