# Generated by Django 5.2.12 on 2026-03-25 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_video_bunny_video_url_alter_video_bunny_embed_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("sinopse", models.TextField(blank=True, verbose_name="Sinopse")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("documentario", "Documentário"),
                            ("livro", "Livro de Arte"),
                            ("institucional", "Institucional"),
                            ("educacional", "Educacional"),
                            ("branded", "Branded Content"),
                            ("outro", "Outro"),
                        ],
                        default="documentario",
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("sustentabilidade", "Sustentabilidade"),
                            ("brasilidade", "Brasilidade"),
                            ("inovacao", "Inovação"),
                            ("cultura", "Cultura"),
                            ("outro", "Outro"),
                        ],
                        default="sustentabilidade",
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "ano",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "duracao",
                    models.CharField(blank=True, max_length=50, verbose_name="Duração"),
                ),
                (
                    "formato",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Formato"
                    ),
                ),
                (
                    "diretor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Diretor(a)"
                    ),
                ),
                (
                    "produtor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Produtor(a)"
                    ),
                ),
                (
                    "fotografia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Fotografia"
                    ),
                ),
                (
                    "edicao",
                    models.CharField(blank=True, max_length=200, verbose_name="Edição"),
                ),
                (
                    "trilha_sonora",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Trilha Sonora"
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem principal do projeto. Recomendado: 16:9 (ex: 1280×720).",
                        upload_to="projetos/posters/",
                        verbose_name="Poster",
                    ),
                ),
                (
                    "bunny_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de embed do Bunny Stream para o filme do projeto.",
                        verbose_name="URL do Player Bunny (iframe)",
                    ),
                ),
                (
                    "patrocinador",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Patrocinador"
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Destaque"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["ordem", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="FotoProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        help_text="Foto do projeto (bastidores, cenas, etc).",
                        upload_to="projetos/fotos/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legenda"
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="core.projeto",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do Projeto",
                "verbose_name_plural": "Fotos do Projeto",
                "ordering": ["ordem"],
            },
        ),
    ]
