# Generated by Django 5.2.12 on 2026-03-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_projeto_fotoprojeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjetoPreAprovado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "conceito",
                    models.TextField(
                        blank=True,
                        help_text="Texto detalhado sobre o conceito do projeto (para página de detalhe).",
                        verbose_name="Conceito",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("documentario", "Documentário"),
                            ("livro", "Livro de Arte e Fotografia"),
                        ],
                        default="documentario",
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("sustentabilidade", "Sustentabilidade"),
                            ("brasilidade", "Brasilidade"),
                            ("diversos", "Diversos"),
                        ],
                        default="sustentabilidade",
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                ("pronac", models.CharField(max_length=20, verbose_name="PRONAC")),
                (
                    "valor",
                    models.CharField(
                        help_text="Ex: R$ 889 mil", max_length=50, verbose_name="Valor"
                    ),
                ),
                (
                    "duracao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 52 min, 70 min, Livro de arte e fotografia",
                        max_length=100,
                        verbose_name="Duração / Formato",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        help_text="Foto principal do projeto para o card.",
                        upload_to="pre_aprovados/fotos/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "contrapartidas",
                    models.TextField(
                        blank=True,
                        help_text="Lista de contrapartidas específicas do projeto (para detalhe).",
                        verbose_name="Contrapartidas",
                    ),
                ),
                (
                    "sobre_autor",
                    models.TextField(
                        blank=True,
                        help_text="Texto sobre o autor/diretor (para detalhe).",
                        verbose_name="Sobre o Autor",
                    ),
                ),
                (
                    "tem_detalhe",
                    models.BooleanField(
                        default=False,
                        help_text="Marque para habilitar a página de detalhe deste projeto.",
                        verbose_name="Tem página de detalhe",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Projeto Pré-Aprovado",
                "verbose_name_plural": "Projetos Pré-Aprovados",
                "ordering": ["categoria", "ordem"],
            },
        ),
    ]
