# Generated by Django 5.2.12 on 2026-03-26 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_projetopreaprovado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotolivro",
            name="imagem",
            field=models.ImageField(
                help_text="Foto do livro para o mosaico (ambientes, detalhes, etc).",
                upload_to="livros/fotos/",
                verbose_name="Imagem",
            ),
        ),
        migrations.CreateModel(
            name="PaginaLivro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        help_text="Scan ou foto da página do livro. Recomendado: proporção da página real (ex: A4).",
                        upload_to="livros/paginas/",
                        verbose_name="Imagem da Página",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paginas",
                        to="core.livro",
                        verbose_name="Livro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Página do Livro",
                "verbose_name_plural": "Páginas do Livro",
                "ordering": ["ordem"],
            },
        ),
    ]
