# Generated by Django 5.2.12 on 2026-03-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_paginalivro"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="link_vendas",
            field=models.URLField(
                blank=True,
                help_text="URL para compra do livro (e-commerce, Amazon, etc).",
                verbose_name="Link de vendas",
            ),
        ),
    ]
