# Generated by Django 5.2.12 on 2026-03-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_link_vendas_to_livro"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="is_serie",
            field=models.BooleanField(
                default=False,
                help_text="Marque se este projeto é uma série com múltiplos episódios.",
                verbose_name="É uma série",
            ),
        ),
        migrations.CreateModel(
            name="Episodio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Episódio"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "bunny_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de embed do Bunny Stream para este episódio.",
                        verbose_name="URL do Player Bunny (iframe)",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem de capa do episódio. Recomendado: 16:9.",
                        upload_to="projetos/episodios/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "duracao",
                    models.CharField(blank=True, max_length=50, verbose_name="Duração"),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodios",
                        to="core.projeto",
                        verbose_name="Projeto (Série)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Episódio",
                "verbose_name_plural": "Episódios",
                "ordering": ["ordem"],
            },
        ),
    ]
